language: rust
rust:
- stable
env:
- MINICONDA_VERSION=4.7.10 RUST_VERSION=stable
os:
- linux
- osx
- windows
cache:
  cargo: true
  pip: true
  directories:
  - "${TRAVIS_HOME}/miniconda3-${MINICONDA_VERSION}"
  - "/c/tools/miniconda3"
install:
- source .travis/install-dependencies-x86_64.sh
script:
- python --version
- python -c "import sys; print(sys.platform)" > "${TRAVIS_OS_NAME}.txt"
deploy:
  provider: releases
  api_key:
    secure: e/BESdiNgknJ0tRATMLubQlrwY0JRiY7jL57tdno8UR+gQ15mutv9bYoaSksei79GNHTs/mNIBV2jkF2zGXaIg77fPSKGe+7E0PiZzUbqdGGj6MPziNdPGtODx87tIWvdPxHEIcUTYzVZ/lsXDI6DOCHx8KdRCQQFLeh3zcwmEcLJtOqW9iUR8TRsTlbDlMJ9nUuRwoLvxIxL/IEt905SCH8GUhpsa+aa1Aj6IT1XaxFdCZjD/HAwX/qCqc+UjRPhXlgFLCGSEfZH+iK+Ky/kVwaC0VPhLuquMWUNLyrwueVOV7BEfGpaIMkbMp+A3S6ToY9ypHLANdbqfJKurfJ/ikjU8RVR4Xz644FNxf1YcZXLfqU8Qdtd0T/F45/7pu2ajApdB4PfOjJfmCLfzruKkyrnbROumS34iXyWGlNLl2gb0zLiJAmzGj0J6j+w3wltK2xTErderfmggeEGvD7qf65EdtLFa0VbM2mmrf3OyP0uiF1tKmwu22ydvAxogcFfdP9GdtUolv4Om4wM2R/9dWQEQzNU7XdcX6z7IW/nMFIGeHK7+wz5qHN+3hT+pU1Z7zPpysswdWi7gyiR/gfDU8KltrF+WoIw0pqCa1vEXbyHo7B0r5XawNmqp7i2OiivA/hqBgJzTlE9vCaFJwJO+KjtXBeIcV4EBa3RwjLzUg=
  skip_cleanup: true
  file_glob: true
  file:
    - "${TRAVIS_OS_NAME}.txt"
  on:
    tags: true
