language: rust
rust:
- stable
env:
- MINICONDA_VERSION=4.7.10 RUST_VERSION=stable
os:
- linux
- osx
- windows
cache:
  cargo: true
  pip: true
  directories:
  - "${TRAVIS_HOME}/miniconda3-${MINICONDA_VERSION}"
  - "/c/tools/miniconda3"
  - "${TRAVIS_BUILD_DIR}/drepr/target"
install:
- source .travis/install-dependencies-x86_64.sh
script:
- python --version
- python -c "import sys; print(sys.platform)" > "${TRAVIS_OS_NAME}.txt"
deploy:
  provider: releases
  api_key:
    secure: mBMXzItkilPgtnkkngosTvzAt3cIPmznNFB/eIJx9dLFOWYOV7yye8suHd3pYxwres3vDGp42kaWJpAs5+fL68B4F6QC+6LevY6cJSwVD5D8S85eygu31fMHqoSS8oigHSvBolyUcGNAH0ur0exAN9krXGM6HMguNNju5LIxD4tRe9OIR73qJuoVBeGFgeWmLiyH/EMjfvionY6Pab7nt0bisEfw55SpkSge4fRmCIYTw+EU/xR4Uz798JUxyLHELnSgn19T1RL5+qnb8VhbtddkXpzJ7f4SP/Dc9LcVcJuhA2JoMKK/KGk8BM7uXfL25H1jLDHb1btkGs4+7wq0cGpeOt/iISMFEvy5YbaVyKx9mwBF+41THRF0Ep6i8FDYyrybu4Ecd8PnaV7iiMU4iWN6C0ioBDtD055HyaLhOmurfvwALx8tEWe5QFTU69Tsi6jsXNEucbFU1Z5Vv1BFRQZqUjtSPLR+HypAR4Bwk40Co16vHsDbOAMh/8UBaxNNo6gE+YjBrsVD4HY3r7WlKLI/RMmX0UmCdRc78zNvJh9qdHrlQDlShJ4pX6qqpPAlN36U1f+Hdc8m9Evr5/71/weD/G9QCTKYkiO9JlDvPioXKARmb+qlLDEbbDMbwSSfoNSVBsHtwQtX2nwnnACXDUmyAylCNt3Y1B69nr6xv9k=
  skip_cleanup: true
  file_glob: true
  file:
    - "${TRAVIS_OS_NAME}.txt"
  on:
    tags: true
