language: rust
rust:
- stable
env:
- MINICONDA_VERSION=4.7.10 RUST_VERSION=stable
os:
- linux
- osx
- windows
cache:
  cargo: true
  pip: true
  directories:
  - "${TRAVIS_HOME}/miniconda3-${MINICONDA_VERSION}"
  - "/c/tools/miniconda3"
install:
- source .travis/install-dependencies-x86_64.sh
script:
- python --version
- python -c "import sys; print(sys.platform)" > "${TRAVIS_OS_NAME}.txt"
deploy:
  provider: releases
  api_key:
    secure: HItHKaYp+ahNgEmwsnZCLD0Lx94JPXnElvzkFq+NnnFMcZdB1usOlTG0nJSbR2cXOgxzDCmRZ4Rhfp1u8ZktcZXJD5ePqMaPjliCA+R2kVssGioIuMHuA1dn7i2XIZPwvyPjeoFPUmj7k2cB3OaRyeMZq6T3BnVFArUf6iVE2Dr7ET80+kyXG/xsZf28LmR9ry2sgPDEKv3Nkky3vGpj/17S/IweDY8YQzvhzQ30ZoKDEbVxMbsP93BxmmtnOysOodXws3NSJakk+poczcGo+/1zL91pLXtdGPKhP5ipJqZ9GGcNp5GIHQas1qpFjApf04DthLfd7u+L0nm825zrfblOhM0PP1gSpkKQRz4mbua9z0VKe3K+Jry8Bqwl/WwI+cJEpLAKe2GX9vkIUtSTnpfGCqxTjuNl08OlA2oAy0UkW0zRiKysDrd35uCuALi0tjOy6InoOK5Lc36KJv8dMDW+Wo8yoMLXco7RuUpXMWac8cjtv9EnR8lcWDpy2V9aigEXXkmDMjfPFHoxSuac+L854uE5JnCETIemFx9FZcnMY1tDP4paNTBnmCuYkO+l/KFKUO7HpU82RLAX+ru9PlZ2M4Q+Ho+ztyYOCq1qC3EknV+gtpkNkwqUXDL4lkDzTjCbATNyQueZkn/ard4LXOyx57Mjhbb+IDlL29gfr6I=
  skip_cleanup: true
  file_glob: true
  file:
    - "${TRAVIS_OS_NAME}.txt"
  on:
    tags: true
