language: rust
rust:
- stable
env:
  global:
  - RUST_VERSION=stable
  - MINICONDA_VERSION=4.7.10
  - CACHE_MINICONDA_DIR=$([ $TRAVIS_OS_NAME = 'windows' ] && echo "/c/tools/miniconda3" || echo "${TRAVIS_HOME}/miniconda3-${MINICONDA_VERSION}")
  - secure: ss40t1AFm1KNTV8OIIBLhyC1sy3hdp1CiXzb1Wi588H9EXM0QR/maU15kk+240Wj5aBqGDi15Lw1yE8UNyXtU9/5bbsRjHp4+H/PfkKPt3nXFXV3yYpHhJwczGWq50zlQvTDnZgzSazVAVBANwoTZwTVhHIoBIpQhJop0JBoSUMNzPfdpLdiBlH7CD4sh1feucAiqpByM2BSKjx60ySvMyuRi2UqIRl+49ywKnLny4TaxEKnuCdKOVY7ycVmKF053YeNKhRul+z+do4MvEEMpIXGusz5tVBjhz5wb4BhC3BnKTg73AH/yQ65UL95JuFVQ9ObfialXOf9riLVt+Pshw/sM9RJDE9aWLhVbcDGz0rB+u6vqLZLgGps1mgFGn3pBCMw93Ll7a0DU708TdxHAxG00DIwALlYINa2LxndVUyHdUe0pd8k36/fDniJh6lZB+O4rAtm5zJzuBi/WStU0rHnBvZTgYcambsKJvpDEYFgJzDidMVTdPSUXR0TGTn6QuIrjc/45TGNyVLE9zq83lgPNunoam5XIyBTpLlwDAK8NZQkZ++eC4HOeBr4OAEk8+vLYsJ/qRSIi8dAMFl+DFDg+C3pSATWOdt6bwmddn7NXTKodLn0uY+E1FuWp9zagqq2MBOLDgxQ1keMOzbwqIdghqwA5apFhDniqWukhqg=
os:
- linux
- osx
- windows
cache:
  cargo: true
  pip: true
  directories:
  - "$CACHE_MINICONDA_DIR"
  - "${TRAVIS_BUILD_DIR}/drepr/target"
install:
- source .travis/install-dependencies-x86_64.sh
script:
- source .travis/build-engine.sh
- export ENGINE_RELEASE_TAG=$(python ${TRAVIS_BUILD_DIR}/pydrepr/devel info --engine_release_tag)
- export ENGINE_FILE_GLOB=$(python ${TRAVIS_BUILD_DIR}/pydrepr/devel info --pre_built_engine_rel_glob)
- ".travis/publish-pypi.sh"
deploy:
  provider: releases
  api_key:
    secure: s/KLgjtdf4rcb2yrxxBBSInebP79gn6FtjsZ7K646VlZ2uJfyBWAlkPsWFuTe+zu/fUY1DIpPnLAFf3t/USxkEVRHgroXSFm+NydxsVKnZxhVqbaEU1gnZErACvluXjojJ9d2JAerzyxtz6f/j4zSpLoEuf9YTeLsfCtj3T6Zyur7zCBcyLU98SbT1y5zFXCa0PkTbJT7sagX1mgvuY83bqWzvJIFQXohOx771qDGe30qJ/OVaVuaBhd4WbFPvsHg+59+voOIV7w/p/+GHUqU2X3CGRSjnMW+xgTwvmrDJM3aynRWlIVXS6GWgpdfiB4rWUJBvDp44FuaAIT/Sl77MrSekRCeK3CCk8xJzLYF77JVCPdTHrLD667Dso2XDoL2EH9PGbZ1dkf9WuGA8XnIa07DsfZ8W74Frnx4T9FZISPcDpo/W/31PEnqFns8HC8GywyX9+MK5ru482kf9o3NzCJNgibSIJEoYpaU4C5d7cUZy887B2pX8wx9T2LZzkFwoSehNte+7m/V7GrsdyhE0mh4tKkuQX7tjsvWcOkqk6PDkvZ5GkKHK/vJ/B1V0sPRu+u/5K64KLF9z2U3y46maEDeJXc4TgWPDwN0ONlOq8zcu4HoANP/ajgEm680u7SVIQgi4W6o9nZ0fOeqecO+Dqo6YZ9bLF6Gv+9/7Y7gbQ=
  skip_cleanup: true
  file_glob: true
  file:
  - "${ENGINE_FILE_GLOB}"
  on:
    tags: true
