language: rust
rust:
  - stable
env:
- MINICONDA_VERSION=4.7.10 RUST_VERSION=stable
os:
  - linux
  - osx
  - windows
cache:
  cargo: true
  pip: true
  directories:
  - "${TRAVIS_HOME}/miniconda3-${MINICONDA_VERSION}"
  - /c/tools/miniconda3
install:
  - source .travis/install-dependencies-x86_64.sh
script:
  - python --version
  # - cd pydrepr
  # - python devel pylib-build
