language: rust
rust:
- stable
env:
- MINICONDA_VERSION=4.7.10 RUST_VERSION=stable
os:
- linux
- osx
- windows
cache:
  cargo: true
  pip: true
  directories:
  - "${TRAVIS_HOME}/miniconda3-${MINICONDA_VERSION}"
  - "/c/tools/miniconda3"
  - "${TRAVIS_BUILD_DIR}/drepr/target"
install:
- source .travis/install-dependencies-x86_64.sh
script:
- python --version
- python -c "import sys; print(sys.platform)" > "${TRAVIS_OS_NAME}.txt"
deploy:
  provider: releases
  api_key:
    secure: xMz1+70FrJSeHNfQaxSSYBz/IS2Eiw327jNLZvy6SbjsJo7HKR0bWJTIRBpvUZKxSMqExgQcZCWBJpCerNxMGpBIzCP5t0G3A/KEa13Z5jPdlOO3yQRp/23iaB5wyauw783AYYXPZLcG4WDSLgyTcF2KlNwj1tqdBxIZCCx0hEtre6ucks1WToGGD5HiFxBFNnsiidlKNvdomRUNiUPZ3AkuZ2SSvXbBkDo0Jt/er7DpvJ4XPocD+HospYmGwfzxypkGuAe3H2Z3dmaRVZdYnxL0tV7pAFxLuffDsa6pEYNAi+IOFeJXLsqcefPL5On/qkdXHBUwrJgIW/uNZVknbfISL9p48s6k8EKZlwCNTDUGP5MK6gpvYkw5qo01JtMg+fpJvOA7TPTEtSpe62QQfxSZbWtTTXgeAgpXqT501QtaM449/4z9PtrkLgkGhvz6fecxbbE+pMQ6wAfoWAlimKtelhUpGDwrfCA9IWbUd0WbILkdG9PzjrZCRHoaXAZ6kcVqrAfzALpGpYtUzIYqnk7wcbBeZOV8gQUKVx7v2y8zosIW4I7S8owCrQRU1bQQrkRDTsNalqqegX8ZyoGFTe769miH4oSbWRBizIeqQ5JCPA7dResrmDpUuvO2cNLS6RbfRgFlsNuk4VuK2rIfGVpeHM5XDXkkMgKjEM1CYk0=
  skip_cleanup: true
  file_glob: true
  file:
    - "${TRAVIS_OS_NAME}.txt"
  on:
    tags: true
