language: rust
rust:
- stable
env:
- MINICONDA_VERSION=4.7.10 RUST_VERSION=stable
os:
- linux
- osx
- windows
cache:
  cargo: true
  pip: true
  directories:
  - "${TRAVIS_HOME}/miniconda3-${MINICONDA_VERSION}"
  - "/c/tools/miniconda3"
  - "${TRAVIS_BUILD_DIR}/drepr/target"
install:
- source .travis/install-dependencies-x86_64.sh
script:
- python --version
- python -c "import sys; print(sys.platform)" > "${TRAVIS_OS_NAME}.txt"
deploy:
  provider: releases
  api_key:
    secure: RJhsXXf+nhNUDKnPTzdBeqXuwIHS76yZhMkt524LjjL85/f99km9N50PBgIsdoaRAsUyw/ELR3+iHMh0LeBuDzYiXOi0H/MMH8A9PeGRUusWYohYtwLsiNuYF2oE/7CFtBJ2qL8pgDtLk7CRnNaUHn21uL0MqgE4pWG990LwrI51UHtxcmBluXkNN3Q2nXs920UYM2bg6F4/hhGEcXhcJivc2FBznvmxHnewC22I0l/fNi65UN3iEFBKx3qLeP3LFJMPtGtzC12VDD5RiceiRgKFfEUkTtYLp7tW8n6xLfnMZp28UfLas0Xkpq+Z8nc/ODAbHhvaOp9fBvxjZErf9/uO5loS7u2Na8YVfKORyIlpQgPsHU1MfRo0OGf8r7dGg9EaX1hl7ZPpnepcU0rf21ATAeM0IvSm2HjWlHgWjzN/uMnhe3u6wXVGP1aKP3cLjA4yuFgcgwN72AfiAe0gloSKaZQ4IaPqfNsTLS1uch4ClqqQ0B885S/ARth3gmcetQkvC9BF1+TOKum8dS060hqULLWcK2XQmEP11iwtgPls3YTIFYg6kkAu6svGw75QRyczpoLJytsrVcGwJcyhb94gdFohjDodABT9l1T4I6U48o/C/Ds+vfQakBc1Dn9gwA7BSpKSlcB4ZACqKl5aDV2BlhkXrheReu8X7O9wbbY=
  skip_cleanup: true
  file_glob: true
  file:
    - "${TRAVIS_OS_NAME}.txt"
  on:
    tags: true
