language: rust
rust:
- stable
env:
  # there is a different between global & matrix
  global:
    - RUST_VERSION=stable
    - MINICONDA_VERSION=4.7.10
    - CACHE_MINICONDA_DIR=$([ $TRAVIS_OS_NAME = 'windows' ] && echo "/c/tools/miniconda3" || echo "${TRAVIS_HOME}/miniconda3-${MINICONDA_VERSION}")
os:
# - linux
# - osx
- windows
cache:
  cargo: true
  pip: true
  directories:
  - "$CACHE_MINICONDA_DIR"
  - "${TRAVIS_BUILD_DIR}/drepr/target"
install:
- source .travis/install-dependencies-x86_64.sh
script:
- source .travis/build-engine.sh
- export MIN_PYLIB_VERSION=$(python ${TRAVIS_BUILD_DIR}/pydrepr/devel info --min_pylib_version_compatible_with_engine)
- echo "${ENGINE_FILE}"
- ls -lah "${ENGINE_FILE}"
deploy:
  provider: releases
  api_key:
    secure: s/KLgjtdf4rcb2yrxxBBSInebP79gn6FtjsZ7K646VlZ2uJfyBWAlkPsWFuTe+zu/fUY1DIpPnLAFf3t/USxkEVRHgroXSFm+NydxsVKnZxhVqbaEU1gnZErACvluXjojJ9d2JAerzyxtz6f/j4zSpLoEuf9YTeLsfCtj3T6Zyur7zCBcyLU98SbT1y5zFXCa0PkTbJT7sagX1mgvuY83bqWzvJIFQXohOx771qDGe30qJ/OVaVuaBhd4WbFPvsHg+59+voOIV7w/p/+GHUqU2X3CGRSjnMW+xgTwvmrDJM3aynRWlIVXS6GWgpdfiB4rWUJBvDp44FuaAIT/Sl77MrSekRCeK3CCk8xJzLYF77JVCPdTHrLD667Dso2XDoL2EH9PGbZ1dkf9WuGA8XnIa07DsfZ8W74Frnx4T9FZISPcDpo/W/31PEnqFns8HC8GywyX9+MK5ru482kf9o3NzCJNgibSIJEoYpaU4C5d7cUZy887B2pX8wx9T2LZzkFwoSehNte+7m/V7GrsdyhE0mh4tKkuQX7tjsvWcOkqk6PDkvZ5GkKHK/vJ/B1V0sPRu+u/5K64KLF9z2U3y46maEDeJXc4TgWPDwN0ONlOq8zcu4HoANP/ajgEm680u7SVIQgi4W6o9nZ0fOeqecO+Dqo6YZ9bLF6Gv+9/7Y7gbQ=
  skip_cleanup: true
  file_glob: true
  file:
    - ./drepr/target/drepr_engine*
  on:
    condition: $MIN_PYLIB_VERSION = "$TRAVIS_TAG"
    tags: true
