language: rust
rust:
- stable
env:
- MINICONDA_VERSION=4.7.10 RUST_VERSION=stable
os:
- linux
- osx
- windows
cache:
  cargo: true
  pip: true
  directories:
  - "${TRAVIS_HOME}/miniconda3-${MINICONDA_VERSION}"
  - "/c/tools/miniconda3"
install:
- source .travis/install-dependencies-x86_64.sh
script:
- python --version
- python -c "import sys; print(sys.platform)" > "${TRAVIS_OS_NAME}.txt"
deploy:
  provider: releases
  api_key:
    secure: sIjhvqTzQCk42nH81MWnVH29CTVbESwDUOKdTq9mv26Zf0MQTIGzZy0jnQPVzHt3KfLMH58xoiW0AK3SW2Atjo7UZg5iphiDt24I3wpebICYLcdMicSEGRreCAYlJLmSW0UAeNfPS7aNx1ip27OsfSK4ijJgWbS+NPRJoUsJ5222L4ww+VvfZdz4sHGRilcnIZU2u1zyUEU6wVlSeTfdWg9fvqRUI60dOnHZr/YLUWDSw8k5sGk3mPD2eGyDXOZzkXYwQMIs31ag6Me3murdaPBCxMyIietic5FMljceedDCznTQQoAIX2CKelk/IzWL/YKYMwlbDPOFvnf9qCEjaqTYvjDADnQ0jO7wwelI8l+BsvkKBFpMRRWkrvLG2mHTYOqat/mbh9d4XEDcU8CQLNCww6gSknol3IaWczeARwCsBv7JF2mMtuNDvSoXRrlprPwCJhBBsO++vJxi6NUIU9Mrr+vMQksWBRdu2Yl8WS3q0+ww+HvwZmSSH5ZWLHWgzS2srCEsHwgL1FLczXVSzVb+hWJUtzqQBWyHBQe5I0UTfQpUo8Qg+YQ5tBqMqgo4LbzDhfn8/63CtBJwB2UcU+99tLOLMPpWx/wA5nbTINAb1cAo5HM8G+QldJk3ePtwMqUO5rn1PCWby3PRsBJjfRL0IMsXuSBkImrkBdAjF3M=
  skip_cleanup: true
  file_glob: true
  file:
    - "${TRAVIS_OS_NAME}.txt"
  on:
    tags: true
