export const ALIGNMENT_UPSERT = "ALIGNMENT_UPSERT";
export type ALIGNMENT_UPSERT = typeof ALIGNMENT_UPSERT;

export const ALIGNMENT_REMOVE = "ALIGNMENT_REMOVE";
export type ALIGNMENT_REMOVE = typeof ALIGNMENT_REMOVE;
